root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "hikvision-anpr-alerts.exe"
  cmd = "make build"
  include_ext = ["go", "tpl", "tmpl", "html", "js", "css", "svg", "png", "jpg", "jpeg", "xml", "env"]
  exclude_dir = [".github", ".run"]
  send_interrupt = true
  stop_on_error = true
  delay = 1000
  kill_delay = 10

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false